name: CMake Build

on:
  # release:
  workflow_dispatch:
    #types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code part 1
        run: |
          apt update
          apt install antlr libantlr-dev -y # ANTLR
          apt install libdap-dev -y # DAP
          apt install bison cmake flex gcc g++ -y # GNU toolchain
          apt install gsl-bin libgsl-dev -y # GSL
          apt install libnetcdf-dev netcdf-bin -y # netCDF
          apt install libudunits2-dev -y # UDUnits
    
      - name: Checkout code part 2
        uses: actions/checkout@v2

      - name: Set up CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests (if applicable)
        run: |
          # Add commands to run tests here

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build

