name: CMake Build

on:
  # release:
  workflow_dispatch:
    #types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code part 1
        run: |
          sudo bash -c "apt update
          apt install -y antlr libantlr-dev
          apt install -y libdap-dev
          apt install -y bison cmake flex gcc g++
          apt install -y gsl-bin libgsl-dev
          apt install -y libnetcdf-dev netcdf-bin
          apt install -y libudunits2-dev
          "
    
      - name: Checkout code part 2
        uses: actions/checkout@v2

      - name: Set up CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests (if applicable)
        run: |
          # Add commands to run tests here

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build

