name: CMake Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests (if applicable)
        run: |
          # Add commands to run tests here

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build

