name: CMake Build

on:
  release:
    types: [published]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo bash -c "apt update
          apt install -y antlr libantlr-dev
          apt install -y libdap-dev
          apt install -y bison cmake flex gcc g++
          apt install -y gsl-bin libgsl-dev
          apt install -y libnetcdf-dev netcdf-bin
          apt install -y libudunits2-dev
          "
    
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Run CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests (if applicable)
        run: |
          # Add commands to run tests here

#you can replace this part with automatic release creation w/ the files we build using https://github.com/marketplace/actions/automatic-releases
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build

